---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: torch
  name: torch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: torch
  template:
    metadata:
      labels:
        app: torch
    spec:
      serviceAccountName: torch
      containers:
      - name: torch
        image: ghcr.io/jrmanes/torch:SET-IT
        command:
          - /bin/sh
          - -c
        args:
          - ./torch --config-file /config/config.yaml
        env:
          - name: HTTP_PORT
            value: "8080"
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"
      - name: otel-agent
        image: otel/opentelemetry-collector-contrib:SET-IT
        command:
          - '/otelcol-contrib'
          - '--config=/conf/otel-agent.yaml'
        volumeMounts:
          - name: otel-agent
            mountPath: "/conf/otel-agent.yaml"
            subPath: otel-agent-celestia.yaml
        ports:
          - name: prometheus-otel
            containerPort: 8888
          - name: prometheus
            containerPort: 9090
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            memory: 200Mi
      volumes:
      - name: config
        configMap:
          name: config
          items:
          - key: config.yaml
            path: config.yaml
      - name: otel-agent
        configMap:
          name: otel-agent
